### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by jpgreth** [solariz/german_stopwords#1]
Perhaps the documentation should be extended.

1. define which criteria makes a stopword a "plain"-stopword and which makes it a "seo"-stopword?
2. add a short how to about contribution 
3. add information how to resort after adding words

**Comment by solariz** [comment]
Added some more README Stuff. Stopwords are  a rather open definition thats why a clear definition of plain and full is a little vague. Always depends on the usage of the list.
